### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by fhsbatista** [fhsbatista/journal#8]
- [x] List areas and their behaviors
- [x] Be able to toggle whether behavior has been performed
- [x] Show total areas score
- [x] Show day average

**Comment by fhsbatista** [comment]
resolved with 8b498
![image](https://github.com/user-attachments/assets/f1fe6b78-aa7d-48dc-bbf9-7138d9bd0d95)
